# akeyshually settings
# Location: ~/.config/akeyshually/config.toml

[settings]
# Enable media key handling (volume, brightness, media controls)
# When false (default): System/DE handles media keys
# When true: akeyshually handles media keys using media-keys.toml
enable_media_keys = false
modifier_release_delay = 50
