# akeyshually settings
# Location: ~/.config/akeyshually/config.toml

[settings]
# Enable media key handling (volume, brightness, media controls)
# When false (default): System/DE handles media keys
# When true: akeyshually handles media keys using media-keys.toml
enable_media_keys = false

# Trigger mode: "press" (default) or "release"
# "press": Execute immediately on key down
# "release": Execute on key release (required for modifier tap detection)
trigger_on = "release"
