# Media key bindings for akeyshually
# Location: ~/.config/akeyshually/media-keys.toml
#
# Only active when enable_media_keys = true in config.toml
#
# Dependencies:
#   - pactl (audio control via PulseAudio/PipeWire)
#   - brightnessctl (brightness control)
#   - playerctl (optional, for media playback control)

[shortcuts]
"volumeup" = "volume_up"
"volumedown" = "volume_down"
"mute" = "mute_toggle"
"brightnessup" = "brightness_up"
"brightnessdown" = "brightness_down"
"playpause" = "media_play_pause"
"nextsong" = "media_next"
"previoussong" = "media_previous"

[commands]
# Audio controls (pactl - PulseAudio/PipeWire)
volume_up = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
volume_down = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
mute_toggle = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

# Brightness controls (brightnessctl)
# Install: sudo apt install brightnessctl
brightness_up = "brightnessctl set +5%"
brightness_down = "brightnessctl set 5%-"

# Media controls (playerctl - MPRIS)
# Install: sudo apt install playerctl
media_play_pause = "playerctl play-pause"
media_next = "playerctl next"
media_previous = "playerctl previous"
